### PR TITLE
Gcov Doxygen support

### PR DESCRIPTION
**Pull request by gerazo**
Finally, I could not improve the IDE settings

### CODE REVIEW

**Review by ip1996 — COMMENTED** [review]
I got error while building the project:
```
CMake Error at CMakeLists.txt:46 (target_link_options):
  Unknown CMake command "target_link_options".
Call Stack (most recent call first):
  CMakeLists.txt:84 (SetupTarget)
```
CMakeError.log:
```
/usr/bin/ld.gold: error: cannot find -lpthreads
CMakeFiles/cmTC_1ebf0.dir/CheckFunctionExists.cxx.o:CheckFunctionExists.cxx:function main: error: undefined reference to 'pthread_create'
```

I think it's because I'm using gcc for compiling the code, but I'm not totally sure in that.
System: Lubuntu 18.04 LTS
Command: ./build.sh

**Comment by gerazo** [comment]
@ip1996 Could you test out the new version?

**Comment by ip1996** [comment]
With CMake upgrade works fine.

**Review by ip1996 — COMMENTED** [review]
Works fine on my machine.
CMake 3.18.2

**Review by ip1996 — APPROVED** [review]

**Pull request merged**
