### PR TITLE
Log analyzer testing

### PR DESCRIPTION
**Pull request by Hossam-Abdin**
I hope the testing and documenting is enough, if I need to do more, please tell me and I can think of more.

### CODE REVIEW

**Review by gerazo — COMMENTED** [review]
I have reviewed the changes and everything seems to be fine.
Except one thing:
Is this directory structure a standard? You always have a test subfolder wherever you have to-be-tested classes. Wouldn't it be better to have a src folder fo all the sources and a test folder on the same level where src is with all the tests in a very same structure? This approach can be much better because of possible packaging reasons later on and as far as I see, the used unittest library could totally do it. Am i missing something?

**Comment by Hossam-Abdin** [comment]
This structure is similar to what I worked with in Nokia and the idea is keeping the tests as near to it is actual files as possible, I can change it if it is not ok

**Comment by gerazo** [comment]
Well, I think it is not good for deployment. If anyone wants to put your analyzer in a standalone place, it brings too much stuff with it. Although we were doing complete test separation also in case of the C++ code.

**Comment by gerazo** [comment]
> Seems like a better ides, should I have a test folder in the same level as src with all the tests inside?

Yes. I think that would fit to the rest of the project best.

**Comment by Hossam-Abdin** [comment]
@gerazo I did seperate the tests in the last commit, I hope it is fine and sorry for the late push

**Review by gerazo — APPROVED** [review]
Excellent work.

**Pull request merged**
